[package]
name = "eadk"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eadk-macros = { git = "https://github.com/LoucaFrss/eadk-macros/", version = "0.1.1" }
